# Generated by Django 4.0.3 on 2022-03-14 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_collection', models.CharField(choices=[('men', 'men'), ('women', 'women'), ('kids', 'kids')], max_length=100)),
                ('product_category', models.CharField(choices=[('cloth', 'cloth'), ('footwear', 'footwear'), ('watchs', 'watchs'), ('accessoies', 'accessoies')], max_length=100)),
                ('product_size', models.CharField(choices=[('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl')], max_length=100)),
                ('product_price', models.PositiveIntegerField()),
                ('product_discription', models.TextField()),
                ('product_image', models.ImageField(upload_to='prodoct_image/')),
                ('product_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
